### PR TITLE
Evaluation of a prefix expression

### PR DESCRIPTION
**Pull request by NiharikaNeha**
This C program evaluates the value of a prefix expression.

Sample Input: ++123
Sample Output: The value of the expression in 6
Working: ++123 = +(1+2)3 = +33 = 3+3 = 6

### CODE REVIEW

**Comment by NiharikaNeha** [comment]
Could you please add the label of hacktober-accepted?

Thanks.

**Comment by Sahil-Bansal-prog** [comment]
What is benefit of it

**Comment by NiharikaNeha** [comment]
It is with respect to the latest update to the Hacktober fest.

The link to the update:
https://hacktoberfest.digitalocean.com/hacktoberfest-update

Thanks.

**Comment by Sahil-Bansal-prog** [comment]
Is this necessary

**Comment by NiharikaNeha** [comment]
Yes, because it does not consider it as a successful pull request unless it
is labelled as 'hacktober-accepted'.

Thanks.

**Comment by NiharikaNeha** [comment]
Your PR was submitted to a repository that is not participating in
Hacktoberfest. Maintainers of the repository can add the "hacktoberfest"
topic to their repository if they wish to participate. Alternatively, an
individual PR can be opted-in with a maintainer adding the
"hacktoberfest-accepted" label to the PR.

The above is the status of my contribution of this project.

Thank You.

**Pull request merged**
